services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "7545:8545"
    command: >
      --deterministic
      --accounts 10
      --host 0.0.0.0
      --port 8545
      --networkId 1337
      --gasLimit 10000000
      --gasPrice 20000000000
      --defaultBalanceEther 100
      --unlock 0
      --secure false
      --db /ganache_data
    volumes:
      - ganache_data:/ganache_data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_password
      POSTGRES_DB: voting_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  ganache_data:
  postgres_data: